### ISSUE TITLE
Request: Tag

### ISSUE THREAD

**Issue by Kutalmis-Bercin** [AlbertoPa/dynamicSmagorinsky#4]
Hello @AlbertoPa 

Could you please add a tag for v2406 so that OpenFOAM submodules can have a non-moving target SHA?

Many thanks.

**Comment by AlbertoPa** [comment]
Hi @Kutalmis-Bercin,

Tagged commit [b5467af](https://github.com/AlbertoPa/dynamicSmagorinsky/commit/b5467af52f61342dc9fb2fa16b034707015ec61f) as OpenFOAM-v2406.

Thanks for including this.
